import Link from "next/link";
import {notFound} from "next/navigation";
import {sourceRegistry,slugify} from "../../../lib/sources";
import {fetchLiveJobs} from "../../../lib/live-jobs";
import {jobs as previewJobs} from "../../../lib/job-data";
const siteUrl="https://usajobmarket.netlify.app";
export const revalidate=900;
export function generateStaticParams(){return sourceRegistry.map(s=>({slug:s.token}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const s=sourceRegistry.find(x=>x.token===slug);if(!s)return {};return {title:`${s.company} Jobs in the USA | USA Job Market`,description:`Find current USA job opportunities at ${s.company}.`,alternates:{canonical:`${siteUrl}/companies/${slug}`}}}
export default async function CompanyPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const s=sourceRegistry.find(x=>x.token===slug);if(!s)notFound();const live=await fetchLiveJobs();const matches=live.filter(j=>slugify(j.company)===slugify(s.company)||j.company.toLowerCase()===s.company.toLowerCase());const result=matches.length?matches:previewJobs.filter(j=>j.company.toLowerCase()===s.company.toLowerCase());const breadcrumb={"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"USA Job Market","item":siteUrl},{"@type":"ListItem","position":2,"name":"Companies","item":siteUrl+"/companies"},{"@type":"ListItem","position":3,"name":s.company,"item":siteUrl+"/companies/"+slug}]};return <main className="directory-page"><div className="container"><span className="eyebrow">USA employer</span><h1>{s.company} Jobs in the USA</h1><p className="directory-intro">Browse {s.company} opportunities available through the configured {s.provider} job feed.</p><div className="results-head"><strong>{result.length} jobs</strong><span>{matches.length?"Live employer data":"Preview data while sources refresh"} • USA only</span></div><div className="jobs-list">{result.map(job=><article className="result-card" key={job.id}><div className="result-logo">{job.company.slice(0,1)}</div><div className="result-body"><Link href={"/jobs/"+job.slug}><h2>{job.title}</h2></Link><p className="result-company">{job.company}</p><p>{job.location} • {job.type}{job.remote?" • Remote":""}</p><div className="result-tags"><span>{job.category}</span>{job.salary&&<span>{job.salary}</span>}</div></div><Link className="btn register" href={"/jobs/"+job.slug}>View Job</Link></article>)}{!result.length&&<div className="empty">No current listings were returned. Check the main USA jobs search for other employers.</div>}</div><div className="seo-band"><div><span className="eyebrow">More employers</span><h2>Explore USA companies</h2><p>Browse all configured employers and search current jobs.</p></div><Link className="btn register" href="/companies">View Companies →</Link></div><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumb)}}/></div></main>}
