import Link from "next/link";
import {notFound} from "next/navigation";
import {usaStates} from "../../../lib/states";
import {filterJobs,jobs} from "../../../lib/job-data";
import {fetchLiveJobs} from "../../../lib/live-jobs";

const siteUrl="https://usajobmarket.netlify.app";
export function generateStaticParams(){return usaStates.map(([slug])=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const s=usaStates.find(x=>x[0]===slug);return s?{title:"Jobs in "+s[1]+" | USA Job Market",description:"Find "+s[1]+" jobs across the United States by category and work type.",alternates:{canonical:siteUrl+"/states/"+slug}}:{title:"State Jobs"};}
export default async function StatePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const s=usaStates.find(x=>x[0]===slug);if(!s)notFound();const live=await fetchLiveJobs();const liveResult=filterJobs({q:s[1]},live);const preview=filterJobs({q:s[1]},jobs);const result=liveResult.length?liveResult:preview;const breadcrumb={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"USA Job Market",item:siteUrl},{"@type":"ListItem",position:2,name:"Jobs by State",item:siteUrl+"/states"},{"@type":"ListItem",position:3,name:s[1],item:siteUrl+"/states/"+slug}]};const intro=liveResult.length?"Browse "+liveResult.length+" live employer listings in "+s[1]+".":"Browse "+preview.length+" preview listings in "+s[1]+" while live sources refresh.";return <main className="directory-page"><div className="container"><Link className="back-link" href="/states">← All states</Link><span className="eyebrow">USA jobs by state</span><h1>Jobs in {s[1]}</h1><p className="directory-intro">{intro}</p><div className="state-job-list">{result.map(job=><Link className="state-job-card" href={"/jobs/"+job.slug} key={job.id}><strong>{job.title}</strong><span>{job.company} • {job.location}</span><small>{job.category} • {job.type}{job.source!=="employer"?" • Live source":" • Preview"}</small></Link>)}{!result.length&&<div className="empty">No current listings found for this state. Check the main USA jobs search for live sources.</div>}</div></div><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumb)}}/></main>;}