import Link from "next/link";
import {categories} from "../../lib/categories";
import {filterJobs,jobs as previewJobs} from "../../lib/job-data";
import {fetchLiveJobs} from "../../lib/live-jobs";

export const revalidate=900;
function qs(values:Record<string,string|undefined>){const p=new URLSearchParams();for(const [k,v] of Object.entries(values))if(v)p.set(k,v);return p.toString();}
export default async function JobsPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const p=await searchParams;
 const val=(k:string)=>Array.isArray(p[k])?p[k][0]:(p[k]??"");
 const q=String(val("q")),location=String(val("location")),category=String(val("category")||"All categories"),type=String(val("type")||"All types"),experience=String(val("experience")||"All experience"),sort=String(val("sort")||"newest"),remote=String(val("remote"))==="true",salaryMin=Number(val("salaryMin")||0),page=Math.max(1,Number(val("page")||1));
 const live=await fetchLiveJobs(); const source=live.length?live:previewJobs;
 const result=filterJobs({q,location,category,type,experience,sort,remote:remote?true:undefined,salaryMin},source);
 const pageSize=20,totalPages=Math.max(1,Math.ceil(result.length/pageSize));const safePage=Math.min(page,totalPages);const visible=result.slice((safePage-1)*pageSize,safePage*pageSize);
 const base={q:q||undefined,location:location||undefined,category:category!=="All categories"?category:undefined,type:type!=="All types"?type:undefined,experience:experience!=="All experience"?experience:undefined,salaryMin:salaryMin?String(salaryMin):undefined,remote:remote?"true":undefined,sort:sort!=="newest"?sort:undefined};
 return <main className="jobs-page"><div className="container jobs-page-head"><span className="eyebrow">USA jobs</span><h1>Find jobs across the United States</h1><p>Search current employer listings by title, company, city, state, category, work type and remote status.</p>
 <form className="jobs-filter-bar" method="get"><input name="q" defaultValue={q} placeholder="Job title, keyword or company"/><input name="location" defaultValue={location} placeholder="City, State or Remote"/><select name="category" defaultValue={category}><option>All categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select><select name="type" defaultValue={type}><option>All types</option><option>Full-time</option><option>Part-time</option><option>Contract</option><option>Internship</option><option>Temporary</option></select><select name="experience" defaultValue={experience}><option>All experience</option><option>Entry-level</option><option>Mid-level</option><option>Senior</option></select><select name="salaryMin" defaultValue={salaryMin||""}><option value="">Any salary</option><option value="40000">$40K+</option><option value="60000">$60K+</option><option value="80000">$80K+</option><option value="100000">$100K+</option></select><label><input type="checkbox" name="remote" value="true" defaultChecked={remote}/> Remote</label><select name="sort" defaultValue={sort}><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="salary">Highest salary</option></select><button className="search-submit" type="submit">Search</button></form></div>
 <div className="container jobs-results"><div className="results-head"><strong>{result.length} jobs</strong><span>{live.length?"Live employer data":"Preview data while sources refresh"} • USA only</span></div><div className="jobs-list">{visible.map(job=><article className="result-card" key={job.id}><div className="result-logo">{job.company.slice(0,1)}</div><div className="result-body"><Link href={"/jobs/"+job.slug}><h2>{job.title}</h2></Link><p className="result-company">{job.company}</p><p>{job.location} • {job.type}{job.remote?" • Remote":""}</p><div className="result-tags"><span>{job.category}</span>{job.experience&&<span>{job.experience}</span>}{job.salary&&<span>{job.salary}</span>}</div></div><Link className="btn register" href={"/jobs/"+job.slug}>View Job</Link></article>)}{!visible.length&&<div className="empty">No jobs found. Try a broader keyword, location or filter.</div>}</div>
 {totalPages>1&&<nav className="pagination" aria-label="Jobs pagination">{safePage>1&&<Link href={"/jobs?"+qs({...base,page:String(safePage-1)})}>← Previous</Link>}<span>Page {safePage} of {totalPages}</span>{safePage<totalPages&&<Link href={"/jobs?"+qs({...base,page:String(safePage+1)})}>Next →</Link>}</nav>}</div></main>;
}